# Generated by Django 4.2.20 on 2025-12-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("MasterApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("forecast_date", models.DateField()),
                ("predicted_qty", models.IntegerField()),
                (
                    "drug_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MasterApp.drug"
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MasterApp.location",
                    ),
                ),
            ],
        ),
    ]
