# Generated by Django 4.2.20 on 2025-12-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("SupplyApp", "0001_initial"),
        ("MasterApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("qty_on_hand", models.IntegerField()),
                ("exp_date", models.DateField()),
                (
                    "batch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SupplyApp.batch",
                    ),
                ),
                (
                    "drug_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MasterApp.drug"
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MasterApp.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsumptionRecord",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("qty_consumed", models.IntegerField()),
                ("consumption_date", models.DateField()),
                (
                    "batch_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="SupplyApp.batch",
                    ),
                ),
                (
                    "drug_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MasterApp.drug"
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MasterApp.location",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="MasterApp.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                (
                    "batch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SupplyApp.batch",
                    ),
                ),
                (
                    "drug_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MasterApp.drug"
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MasterApp.location",
                    ),
                ),
            ],
        ),
    ]
