# Generated by Django 4.2.20 on 2025-12-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("SupplyApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainTransaction",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("tx_hash", models.CharField(max_length=255)),
                ("tx_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField()),
                (
                    "batch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SupplyApp.batch",
                    ),
                ),
            ],
        ),
    ]
