# Generated by Django 5.0.2 on 2026-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlockchainApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blockchaintransaction",
            name="batch_id",
        ),
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="tx_hash",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
