# Generated by Django 4.2.20 on 2025-12-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("MasterApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("order_number", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("carrier_name", models.CharField(max_length=100)),
                ("tracking_number", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="MasterApp.user",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_sent",
                        to="MasterApp.location",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_received",
                        to="MasterApp.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("qty", models.IntegerField()),
                (
                    "drug_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MasterApp.drug"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SupplyApp.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("mfg_date", models.DateField()),
                ("exp_date", models.DateField()),
                ("blockchain_hash", models.CharField(max_length=255)),
                ("qr_code_data", models.TextField()),
                (
                    "drug_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="MasterApp.drug"
                    ),
                ),
            ],
        ),
    ]
