# Generated by Django 5.0.2 on 2026-02-20 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SupplyApp", "0002_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_block_hash",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_block_hash",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_block_hash",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="batch_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="SupplyApp.batch",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="batch",
            name="blockchain_hash",
            field=models.TextField(),
        ),
    ]
