# Generated by Django 5.0.2 on 2026-02-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "SupplyApp",
            "0003_order_delivered_block_hash_order_order_block_hash_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_block_hash",
            field=models.TextField(null=True),
        ),
    ]
