# Generated by Django 5.0.2 on 2026-03-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SupplyApp", "0004_order_cancelled_at_order_cancelled_block_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="qr_code_data",
        ),
    ]
