# Generated by Django 5.0.2 on 2026-03-31 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SupplyApp", "0005_remove_batch_qr_code_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="batch_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SupplyApp.batch",
            ),
        ),
    ]
